version: '3'
services:
  app:
    container_name: full_app
    build:
      context: .
      dockerfile: D:\Projects\go\src\turkdev\DockerFile
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres # Uncomment this when using postgres.
      # - fullstack-mysql           # Uncomment this when using mysql.
    networks:
      - fullstack

  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - DATABASE_HOST=${DBHost}
      - POSTGRES_USER=${DBUser}
      - POSTGRES_PASSWORD=${DBPassword}
      - POSTGRES_DB=${DBName}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGAdminDefaultEmail}
      PGADMIN_DEFAULT_PASSWORD: ${PGAdminDefaultPassword}
    depends_on:
      - fullstack-postgres
    ports:
      - '5050:80'
    networks:
      - fullstack
    restart: unless-stopped

volumes:
  api:
  database_postgres: # Uncomment this when using postgres.

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
