version: '3'
services:
  db:
    image: postgres:latest
    container_name: turkdev_db
    build:
      context: .
      dockerfile: ./src/data/DockerFile
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    container_name: turkdev_app
    env_file:
      - ./.env
    build:
      context: .
      args:
        app_env: ${APP_ENV}
      dockerfile: DockerFile
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/go/src/turkdev/api
    depends_on:
      - db

  pgadmin:
    container_name: turkdev_pg
    image: dpage/pgadmin4
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - db
    ports:
      - '5050:80'
    restart: unless-stopped

volumes:
  api:
  pgdata:
