version: '3'
services:
  db:
    image: postgres:latest
    container_name: turkdev_db
    build:
      context: .
      dockerfile: ./src/data/DockerFile
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DBUser}
      - POSTGRES_PASSWORD=${DBPassword}
      - POSTGRES_DB=${DBName}
      - PGDATA=/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  app:
    container_name: turkdev_app
    build:
      context: .
      args:
        app_env: ${APP_ENV}
      dockerfile: DockerFile.dev
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/go/src/turkdev/api
    depends_on:
      - db

  pgadmin:
    container_name: turkdev_pg
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGAdminDefaultEmail}
      PGADMIN_DEFAULT_PASSWORD: ${PGAdminDefaultPassword}
    depends_on:
      - db
    ports:
      - '5050:80'
    restart: unless-stopped

volumes:
  api:
  pgdata:
