version: '3'
services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/etc/nginx:/etc/nginx/vhost.d'
      - '/usr/share/nginx/html:/usr/share/nginx/html'
      - 'certs:/etc/nginx/certs:ro'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
    networks:
      - default
      - nginx-proxy

  nginx-letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx-proxy
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - 'certs:/etc/nginx/certs:rw'
      - '/etc/nginx:/etc/nginx/vhost.d'
      - '/usr/share/nginx/html:/usr/share/nginx/html'

  db:
    image: postgres:latest
    container_name: linkwind_db
    build:
      context: .
      dockerfile: db.prod.dockerfile
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=/pgdata
    volumes:
      - ./app/data/pgdata:/var/lib/postgresql/data

  app:
    container_name: linkwind_app
    env_file:
      - .env
    build:
      context: .
      args:
        app_env: ${APP_ENV}
      dockerfile: app.prod.dockerfile
    environment:
      - VIRTUAL_HOST=app.linkwind.co
      - VIRTUAL_PORT=${APP_PORT}
      - LETSENCRYPT_HOST=app.linkwind.co
    #ports:
    #  - ${APP_PORT}:${APP_PORT}
    restart: on-failure
    volumes:
      - app:/go/src/linkwind/app
    depends_on:
      - db
    networks:
      - default
      - nginx-proxy

  pgadmin:
    container_name: linkwind_pg
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - db
    ports:
      - ${PG_ADMIN_PORT}:${PG_ADMIN_PORT}
    restart: unless-stopped

  web:
    container_name: linkwind_web
    env_file:
      - .env
    build:
      context: .
      args:
        app_env: ${APP_ENV}
      dockerfile: web.prod.dockerfile
    environment:
      - VIRTUAL_HOST=linkwind.co
      - LETSENCRYPT_HOST=linkwind.co
    #ports:
    #  - ${WEB_SITE_PORT}:${WEB_SITE_PORT}
    restart: on-failure
    depends_on:
      - db

volumes:
  app:
  pgdata:
  certs:

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
