FROM nginx:alpine
COPY . /usr/share/nginx/html

#uncomment this when we have configuration
#COPY conf /etc/nginx

#VOLUME /usr/share/nginx/html
#VOLUME /etc/nginx
#VOLUME /var/log/nginx/log

# Expose port 80 to the outside world
EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"] --port 80